"""удаление столба usres_orders из таблицы users

Revision ID: 157d75e40a7d
Revises: 
Create Date: 2025-03-08 21:56:31.852723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157d75e40a7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_orders_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'user_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_orders', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_user_orders_fkey', 'users', 'models', ['user_orders'], ['id'])
    # ### end Alembic commands ###
